#tomcat 配置

server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

#数据源信息配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9980/foodie-shop-study?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

#mybatis 配置
mybatis:
  type-aliases-package: com.howard.pojo
  mapper-locations: classpath:mapper/*.xml

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.howard.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL